### PR TITLE
Changes to export in display order.

### PR DESCRIPTION
**Pull request by ymstmsys**
I changed to export issues in display order which is same as other exporters.

### CODE REVIEW

**Comment by two-pack** [comment]
Thank you for requesting.  
Could you make tests for your request?

**Comment by two-pack** [comment]
I reproduced this problem. Thank you again for reporting it :)

When I created this plugin, I referred to app/controllers/issues_controller.rb. Because I want to get same result of CSV export of Redmine default function.
So I think sort parameters are added to URL of XLSX export.
I'm trying to implement it, but need to more time :(

**Comment by two-pack** [comment]
I implemented exporting xlsx with sort.
I plan to merge after CI test.

**Comment by two-pack** [comment]
I missed merging operation on #19 :(
But merged now.

**Comment by ymstmsys** [comment]
Thanks!
I confirmed that exporting satisfactorily.

**Pull request merged**
