### PR TITLE
Update _view_issues_index_bottom.erb

### PR DESCRIPTION
**Pull request by lilewis**
undefined method `query_as_hidden_field_tags'  in Redmine 3.2.0.stable

### CODE REVIEW

**Comment by two-pack** [comment]
I could reproduce this problem in Redmine 3.2.0 when I exported issues.

But I think not good how to fix it to compare Redmine::VERSION::STRING.
I create another fix patch to 34d3a78 . lilewis, Can you check it?

BTW in old Redmine like 3.2.0, issues filter function is not applied. see following:
#20 , and http://www.redmine.org/issues/22108

**Comment by two-pack** [comment]
My fix has bug ;( I fix again on same branch.

**Comment by undancer** [comment]
`if Redmine::VERSION::MAJOR >= 3 and Redmine::VERSION::MINOR >= 2 and Redmine::VERSION::TINY >= 1`
3.3.0 == false

**Comment by two-pack** [comment]
undancer,
Already fix it. Thx checking :)

**Comment by undancer** [comment]
but 4.0.0 == false

so

```ruby
if ((Redmine::VERSION::MAJOR > 3) || (Redmine::VERSION::MAJOR == 3 && Redmine::VERSION::MINOR > 2) || (Redmine::VERSION::MAJOR == 3 && Redmine::VERSION::MINOR == 2 && Redmine::VERSION::TINY >= 1))
```

**Comment by two-pack** [comment]
@undancer ,
Please try following:
https://github.com/two-pack/redmine_xlsx_format_issue_exporter/tree/%2322?files=1

I change condition redmine version to existing method.

**Comment by undancer** [comment]
👍

**Comment by lilewis** [comment]
Sorry,I just can't  see it now,
Thanks to  @undancer @two-pack  for  my help
You are all very 👍👍👍👍👍👍

**Comment by two-pack** [comment]
I merged the patch. Thanks for reporting and responsing :)

**Pull request closed without merging**
